version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MySAMLambdaStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18p2z839med2y"
s3_prefix = "MySAMLambdaStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
